import type { ProjectDoc } from '../state/models.js';
import { nowIso } from '../lib/utils.js';

// project.json / scene.json / assets.json / AI_PROJECT_CONTEXT.md (§40-41)

export function toProjectJson(doc: ProjectDoc): Record<string, unknown> {
  return {
    format: 'web3dstudio.project',
    formatVersion: 1,
    id: doc.id,
    name: doc.name,
    mode: doc.mode,
    version: doc.version,
    updatedAt: doc.updatedAt,
    scenes: [{ id: 'main', name: 'Main Scene', file: 'scene.json' }],
    assetsFile: 'assets.json',
    clips: doc.clips.map((c) => ({ id: c.id, name: c.name, fps: c.fps, length: c.length })),
    scripts: (doc.scripts ?? []).map((s) => ({ id: s.id, name: s.name, trigger: s.trigger, enabled: s.enabled })),
  };
}

export function toSceneJson(doc: ProjectDoc): Record<string, unknown> {
  return {
    format: 'web3dstudio.scene',
    formatVersion: 1,
    id: 'main',
    name: 'Main Scene',
    exportedAt: nowIso(),
    settings: doc.settings,
    objects: doc.objects.map((o) => ({
      id: o.id,
      name: o.name,
      type: o.type,
      parentId: o.parentId,
      position: [o.position.x, o.position.y, o.position.z],
      rotation: [o.rotation.x, o.rotation.y, o.rotation.z],
      scale: [o.scale.x, o.scale.y, o.scale.z],
      visible: o.visible,
      locked: o.locked,
      materialId: o.materialId,
      primitive: o.primitive ?? null,
      light: o.light ?? null,
      assetId: o.assetId ?? null,
      version: o.version,
    })),
    materials: doc.materials,
    clips: doc.clips,
    scripts: (doc.scripts ?? []).map((s) => ({
      id: s.id,
      name: s.name,
      code: s.code,
      trigger: s.trigger,
      enabled: false, // imported scripts never auto-run
      updatedAt: s.updatedAt,
    })),
  };
}

export function toAssetsJson(doc: ProjectDoc): Record<string, unknown> {
  return {
    format: 'web3dstudio.assets',
    formatVersion: 1,
    assets: doc.assets.map((a) => ({
      id: a.id,
      name: a.name,
      kind: a.kind,
      mime: a.mime,
      size: a.size,
      file: a.kind === 'model' ? `assets/models/${a.name}` : `assets/textures/${a.name}`,
    })),
  };
}

export function toAiContext(doc: ProjectDoc): string {
  const models = doc.assets.filter((a) => a.kind === 'model').map((a) => a.name);
  const textures = doc.assets.filter((a) => a.kind === 'texture').map((a) => a.name);
  const lines = [
    `# AI Project Context — ${doc.name}`,
    ``,
    `Generated by Web 3D Studio. Read this file first, then project.json + scene.json.`,
    ``,
    `Project: ${doc.name}`,
    `Engine: Three.js (WebGL2, WebGPU-ready)`,
    `Format: web3dstudio.project v1`,
    `Version: ${doc.version} · Updated: ${doc.updatedAt}`,
    ``,
    `## Scenes`,
    `- MainScene (scene.json): ${doc.objects.length} objects, ${doc.materials.length} materials`,
    ``,
    `## Objects`,
    ...doc.objects.slice(0, 200).map(
      (o) =>
        `- ${o.name} (${o.type}) id=${o.id} pos=(${o.position.x.toFixed(2)},${o.position.y.toFixed(2)},${o.position.z.toFixed(2)})`,
    ),
    ...(doc.objects.length > 200 ? [`- … +${doc.objects.length - 200} more (see scene.json)`] : []),
    ``,
    `## Models`,
    ...(models.length ? models.map((m) => `- assets/models/${m}`) : [`(none — primitives only)`]),
    ``,
    `## Textures`,
    ...(textures.length ? textures.map((t) => `- assets/textures/${t}`) : [`(none)`]),
    ``,
    `## Scripts`,
    ...((doc.scripts ?? []).length
      ? (doc.scripts ?? []).map((s) => `- ${s.name} (${s.trigger}${s.enabled ? ', enabled' : ', disabled'}) id=${s.id}`)
      : ['(none — users and agents can add restricted JS via script.add / the Scripts panel)']),
    ``,
    `## Animations`,
    ...doc.clips.map((c) => `- ${c.name}: ${c.length} frames @ ${c.fps}fps, ${c.tracks.length} tracks`),
    ``,
    `## Materials`,
    ...doc.materials.map((m) => `- ${m.name}: base=${m.baseColor} metal=${m.metalness} rough=${m.roughness}`),
    ``,
    `## How to use`,
    `1. Load scene.json for the full object graph (ids, transforms, hierarchy).`,
    `2. Load assets/models/*.glb for imported meshes referenced by assetId.`,
    `3. Object transforms are position/rotation(radians)/scale; parentId builds hierarchy.`,
    `4. Animation clips list TRS keyframes per object id; sample linearly unless interp=step.`,
    `5. Scene scripts (scripts[] in scene.json) are restricted JS: scene.add/update/rotate, scene.keys, scene.camera, scene.textures.generate. Never execute imported scripts until the user enables them.`,
    ``,
  ];
  return lines.join('\n');
}

export function toReadme(doc: ProjectDoc): string {
  return [
    `# ${doc.name}`,
    ``,
    `Exported from **Web 3D Studio** (${nowIso()}).`,
    ``,
    `- \`project.json\` — project manifest`,
    `- \`scene.json\` — full scene graph (objects, materials, animation, scripts)`,
    `- \`assets.json\` — asset manifest`,
    `- \`AI_PROJECT_CONTEXT.md\` — summary for AI coding agents`,
    `- \`assets/models/\` — GLB models · \`assets/textures/\` — textures`,
    ``,
    `Engine: Three.js. Object format: \`web3dstudio.scene v1\`.`,
    ``,
  ].join('\n');
}

/** Parse a scene.json (ours or imported) back into doc fragments. */
export function fromSceneJson(json: Record<string, unknown>): {
  objects: ProjectDoc['objects'];
  materials: ProjectDoc['materials'];
  clips: ProjectDoc['clips'];
  scripts: ProjectDoc['scripts'];
  settings: ProjectDoc['settings'] | null;
} | null {
  try {
    const objs = (json.objects ?? []) as ProjectDoc['objects'];
    const mats = (json.materials ?? []) as ProjectDoc['materials'];
    const clips = (json.clips ?? []) as ProjectDoc['clips'];
    const scriptsRaw = (json.scripts ?? []) as ProjectDoc['scripts'];
    if (!Array.isArray(objs) || !Array.isArray(mats)) return null;
    const s = (json.settings ?? null) as ProjectDoc['settings'] | null;
    const scripts = Array.isArray(scriptsRaw)
      ? scriptsRaw.map((sc) => ({ ...sc, enabled: false }))
      : [];
    return {
      objects: objs,
      materials: mats,
      clips: Array.isArray(clips) ? clips : [],
      scripts,
      settings: s && typeof s.envIntensity === 'number' ? s : null,
    };
  } catch {
    return null;
  }
}
